### PR TITLE
Deal with pinned tabs

### PR DESCRIPTION
**Pull request by jwoos**
Might want to move the utils into a separate file, so it can be reused in other files as well.

I opted to use ES6 features because it's a Chrome extension and chrome supports most of the spec.

### CODE REVIEW

**Comment by jwoos** [comment]
Updated pull request to deal with pinned tabs - address #8 . There are two possible cases:

1. Moving a pinned tab
At the leftmost position, it will then moved to its rightmost position (right before a normal tab). When right before a normal tab and it's attempted to move to the right, it'll instead be placed in the leftmost position.
2. Moving a normal tab
At the leftmost position (right after a pinned tab), it will be moved to the rightmost position if attempted to be move to the left. If attempted to be moved to the right at the rightmost position, it will be placed at the leftmost position.

**Comment by dqgorelick** [comment]
LGTM! @bigolu look at @jwoos 's additions~

**Comment by dqgorelick** [comment]
it works on pinned tabs now :D

**Comment by bigolu** [comment]
Sick, looks really good!

**Pull request merged**
